export const metadata = {
  title: "Privacy Policy | Sentient Index Labs & Technology",
  description:
    "Privacy practices for Sentient Index Labs & Technology (SILT).",
};

export default function PrivacyPage() {
  return (
    <div style={{ maxWidth: 880 }}>
      <h1>Privacy Policy</h1>

      <p>
        Sentient Index Labs &amp; Technology (SILT) is committed to handling
        information responsibly and with appropriate restraint. This policy
        describes our general approach to privacy for this website.
      </p>

      <h2>Information we collect</h2>
      <p>
        This site does not intentionally collect personal information from
        visitors. Information may be provided voluntarily if you contact us
        via email.
      </p>

      <h2>Use of information</h2>
      <p>
        Any information provided to SILT is used solely for the purpose of
        responding to inquiries, supporting governance discussions, or
        maintaining operational records.
      </p>

      <h2>Analytics and logs</h2>
      <p>
        Basic technical logs (such as IP addresses or request metadata) may be
        generated by hosting providers for security and operational purposes.
        SILT does not use this information for profiling or advertising.
      </p>

      <h2>Data retention</h2>
      <p>
        Information is retained only as long as reasonably necessary for
        operational or governance purposes.
      </p>

      <h2>Third-party services</h2>
      <p>
        This site may be hosted by third-party infrastructure providers.
        SILT does not control their internal data handling practices.
      </p>

      <h2>Contact</h2>
      <p>
        Privacy-related inquiries may be directed to:
        <br />
        <strong>info@sentientindexlabs.com</strong>
      </p>

      <p style={{ fontSize: 14, color: "#5a5a5a" }}>
        This policy is informational and may be updated without notice.
      </p>
    </div>
  );
}
